name: Update Widget
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python update_widget.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Daily widget update
          file_pattern: "widget.json"